config/routes.rb
Rails.application.routes.draw do

  resources :technologies
  root 'welcome#index'

  resources :examples
  resources :meetups, only: [ :new, :create ]

end

app/models/example.rb
class Example < ActiveRecord::Base
end

app/models/meetup.rb
class Meetup < ActiveRecord::Base
  serialize :guests, JSON

  def guests=(guests)
    puts guests.inspect
    super( guests.select(&:present?).map(&:strip) )
    puts guests.inspect
  end
end

app/models/technology.rb
class Technology < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/examples_controller.rb
class ExamplesController < ApplicationController
  before_action :set_example, only: [:show, :edit, :update, :destroy]

  # GET /examples
  # GET /examples.json
  def index
    @examples = Example.all
  end

  # GET /examples/1
  # GET /examples/1.json
  def show
    @technologies = Technology.all.to_a
  end

  # GET /examples/new
  def new
    @example = Example.new
  end

  # GET /examples/1/edit
  def edit
  end

  # POST /examples
  # POST /examples.json
  def create
    @example = Example.new(example_params)

    respond_to do |format|
      if @example.save
        format.html { redirect_to @example, notice: 'Example was successfully created.' }
        format.json { render :show, status: :created, location: @example }
      else
        format.html { render :new }
        format.json { render json: @example.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /examples/1
  # PATCH/PUT /examples/1.json
  def update
    respond_to do |format|
      if @example.update(example_params)
        format.html { redirect_to @example, notice: 'Example was successfully updated.' }
        format.json { render :show, status: :ok, location: @example }
      else
        format.html { render :edit }
        format.json { render json: @example.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /examples/1
  # DELETE /examples/1.json
  def destroy
    @example.destroy
    respond_to do |format|
      format.html { redirect_to examples_url, notice: 'Example was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_example
      @example = Example.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def example_params
      params.require(:example).permit(:name, :react_component_name)
    end
end

app/controllers/meetups_controller.rb
class MeetupsController < ApplicationController
  def new
  end

  def create
    @meetup = Meetup.new(meetup_params)

    respond_to do |format|

      if @meetup.save
        format.html { redirect_to @meetup, notice: 'Meetup was successfully created' }
        format.json { render json: @meetup, status: 200 }
      else
        format.html { render :new }
        format.json { render json: @meetup.errors, status: :unprocessable_entity }
      end

    end
  end

  private
  def meetup_params
    params.require(:meetup).permit(:title, :description, :date, :seo, :technology, guests: [])
  end
end

app/controllers/technologies_controller.rb
class TechnologiesController < ApplicationController
  before_action :set_technology, only: [:show, :edit, :update, :destroy]

  # GET /technologies
  # GET /technologies.json
  def index
    @technologies = Technology.all
  end

  # GET /technologies/1
  # GET /technologies/1.json
  def show
  end

  # GET /technologies/new
  def new
    @technology = Technology.new
  end

  # GET /technologies/1/edit
  def edit
  end

  # POST /technologies
  # POST /technologies.json
  def create
    @technology = Technology.new(technology_params)

    respond_to do |format|
      if @technology.save
        format.html { redirect_to @technology, notice: 'Technology was successfully created.' }
        format.json { render :show, status: :created, location: @technology }
      else
        format.html { render :new }
        format.json { render json: @technology.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /technologies/1
  # PATCH/PUT /technologies/1.json
  def update
    respond_to do |format|
      if @technology.update(technology_params)
        format.html { redirect_to @technology, notice: 'Technology was successfully updated.' }
        format.json { render :show, status: :ok, location: @technology }
      else
        format.html { render :edit }
        format.json { render json: @technology.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /technologies/1
  # DELETE /technologies/1.json
  def destroy
    @technology.destroy
    respond_to do |format|
      format.html { redirect_to technologies_url, notice: 'Technology was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_technology
      @technology = Technology.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def technology_params
      params.require(:technology).permit(:name)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @examples = Example.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/examples_helper.rb
module ExamplesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/examples/_form.html.haml
= form_for @example do |f|
  - if @example.errors.any?
    #error_explanation
      %h2= "#{pluralize(@example.errors.count, "error")} prohibited this example from being saved:"
      %ul
        - @example.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
    %br
    = f.label :react_component_name
    = f.text_field :react_component_name
  .actions
    = f.submit 'Save'

app/views/examples/edit.html.haml
%h1 Editing example

= render 'form'

= link_to 'Show', @example
\|
= link_to 'Back', examples_path

app/views/examples/index.html.haml
%h1 Listing examples

%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th

  %tbody
    - @examples.each do |example|
      %tr
        %td= example.name
        %td= link_to 'Show', example
        %td= link_to 'Edit', edit_example_path(example)
        %td= link_to 'Destroy', example, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Example', new_example_path

app/views/examples/new.html.haml
%h1 New example

= render 'form'

= link_to 'Back', examples_path

app/views/examples/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @example.name
  %br
  %b React Component Name:
  = @example.react_component_name
  %br
  %br
  - if @example.name == 'Simple Link Example'
    %div{ id: @example.name.gsub!(/( )/, '_').downcase! }
  - else
    - case @example.name
    - when 'Validation Example'
      - props = { name: 'test', type: 'experimental', content: 'blog post content here.', date: '10-30-1973'} 
    - else
      - props = { technologies: @technologies }

    = react_component(@example.react_component_name, props, {class: "container"})
  %br
  %br
  -# - file_name = Rails.root.join('app', 'assets', 'javascripts', 'examples', "example_#{@example.id}.coffee")
  -# = File.read(file_name)

= link_to 'Edit', edit_example_path(@example)
\|
= link_to 'Back', examples_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ReactPlaygroundApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/meetups/new.html.haml
%h1 Meetups#new
%p Find me in app/views/meetups/new.html.haml

app/views/technologies/_form.html.haml
= form_for @technology do |f|
  - if @technology.errors.any?
    #error_explanation
      %h2= "#{pluralize(@technology.errors.count, "error")} prohibited this technology from being saved:"
      %ul
        - @technology.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/technologies/edit.html.haml
%h1 Editing technology

= render 'form'

= link_to 'Show', @technology
\|
= link_to 'Back', technologies_path

app/views/technologies/index.html.haml
%h1 Listing technologies

%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th

  %tbody
    - @technologies.each do |technology|
      %tr
        %td= technology.name
        %td= link_to 'Show', technology
        %td= link_to 'Edit', edit_technology_path(technology)
        %td= link_to 'Destroy', technology, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Technology', new_technology_path

app/views/technologies/new.html.haml
%h1 New technology

= render 'form'

= link_to 'Back', technologies_path

app/views/technologies/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @technology.name

= link_to 'Edit', edit_technology_path(@technology)
\|
= link_to 'Back', technologies_path

app/views/welcome/index.html.haml
%h1 Listing examples

%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th

  %tbody
    - @examples.each do |example|
      %tr
        %td= example.name
        %td= link_to 'Show', example
        %td= link_to 'Edit', edit_example_path(example)
        %td= link_to 'Destroy', example, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Example', new_example_path